name: Test Creds

on: workflow_dispatch


# Test from https://registry.terraform.io/modules/unfunco/oidc-github/aws/latest
jobs:
  aws-caller-identity:
    name: Check caller identity
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ env.AWS_REGION }}
        role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/github
    - run: aws sts get-caller-identity

# TODO: need HCP Creds next
